// Code generated by goctl. DO NOT EDIT.
// Source: orders.proto

package ordersclient

import (
	"context"

	"lab-zero/orders/orders"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetOrdersByUserIdRequest  = orders.GetOrdersByUserIdRequest
	GetOrdersByUserIdResponse = orders.GetOrdersByUserIdResponse
	UserOrders                = orders.UserOrders

	Orders interface {
		GetOrdersByUserId(ctx context.Context, in *GetOrdersByUserIdRequest, opts ...grpc.CallOption) (*GetOrdersByUserIdResponse, error)
	}

	defaultOrders struct {
		cli zrpc.Client
	}
)

func NewOrders(cli zrpc.Client) Orders {
	return &defaultOrders{
		cli: cli,
	}
}

func (m *defaultOrders) GetOrdersByUserId(ctx context.Context, in *GetOrdersByUserIdRequest, opts ...grpc.CallOption) (*GetOrdersByUserIdResponse, error) {
	client := orders.NewOrdersClient(m.cli.Conn())
	return client.GetOrdersByUserId(ctx, in, opts...)
}
