// Code generated by goctl. DO NOT EDIT.
// Source: orders.proto

package server

import (
	"context"

	"lab-zero/orders/internal/logic"
	"lab-zero/orders/internal/svc"
	"lab-zero/orders/orders"
)

type OrdersServer struct {
	svcCtx *svc.ServiceContext
	orders.UnimplementedOrdersServer
}

func NewOrdersServer(svcCtx *svc.ServiceContext) *OrdersServer {
	return &OrdersServer{
		svcCtx: svcCtx,
	}
}

func (s *OrdersServer) GetOrdersByUserId(ctx context.Context, in *orders.GetOrdersByUserIdRequest) (*orders.GetOrdersByUserIdResponse, error) {
	l := logic.NewGetOrdersByUserIdLogic(ctx, s.svcCtx)
	return l.GetOrdersByUserId(in)
}
