// Code generated by goctl. DO NOT EDIT.
// Source: users.proto

package usersclient

import (
	"context"

	"lab-zero/users/users"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserInfoRequest  = users.GetUserInfoRequest
	GetUserInfoResponse = users.GetUserInfoResponse
	UserOrders          = users.UserOrders

	Users interface {
		GetUserInfoById(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) GetUserInfoById(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserInfoById(ctx, in, opts...)
}
